/**
 * PdfReport.tsx
 * Generates a professional government-style PDF report.
 * Uses a simple HTML string approach (no ReactDOM.createRoot in popup)
 * to avoid the blank-page timing issue with window.print() firing
 * before React finishes rendering.
 */
import { CitizenProfile, SchemeRecommendation } from '../services/api';
import { Language } from '../i18n/translations';

interface PdfReportOptions {
  profile: CitizenProfile;
  recommendations: SchemeRecommendation[];
  applicationId: string;
  generatedDate: string;
  language: Language;
  conversationSummary?: string;
}

const L = {
  en: {
    title: 'Government Scheme Recommendation Report',
    appId: 'Application ID', generated: 'Generated', lang: 'Language', citizen: 'Citizen',
    langName: 'English',
    profileTitle: 'Citizen Profile',
    fields: { name: 'Full Name', age: 'Age', gender: 'Gender', state: 'State', category: 'Category', occupation: 'Occupation', income: 'Annual Income', disability: 'Disability', marital: 'Marital Status' },
    yes: 'Yes', no: 'No',
    schemesTitle: 'Recommended Schemes', noSchemes: 'No schemes found.',
    rank: 'Rank', score: 'Score', benefits: 'Benefits', eligibility: 'Eligibility',
    documents: 'Documents', application: 'How to Apply', matchReasons: 'Match Reasons',
    summaryTitle: 'Application Summary',
    footerBrand: 'Generated by Sahayak AI',
    disclaimer: 'This report is for informational purposes only. Official eligibility is determined by the respective government department.',
    qr: 'QR', page: 'Page 1',
  },
  hi: {
    title: 'सरकारी योजना अनुशंसा रिपोर्ट',
    appId: 'आवेदन ID', generated: 'तिथि', lang: 'भाषा', citizen: 'नागरिक',
    langName: 'हिंदी',
    profileTitle: 'नागरिक प्रोफ़ाइल',
    fields: { name: 'पूरा नाम', age: 'आयु', gender: 'लिंग', state: 'राज्य', category: 'श्रेणी', occupation: 'व्यवसाय', income: 'वार्षिक आय', disability: 'विकलांगता', marital: 'वैवाहिक स्थिति' },
    yes: 'हाँ', no: 'नहीं',
    schemesTitle: 'अनुशंसित योजनाएं', noSchemes: 'कोई योजना नहीं मिली।',
    rank: 'क्रम', score: 'स्कोर', benefits: 'लाभ', eligibility: 'पात्रता',
    documents: 'दस्तावेज़', application: 'आवेदन कैसे करें', matchReasons: 'मिलान के कारण',
    summaryTitle: 'आवेदन सारांश',
    footerBrand: 'सहायक AI द्वारा निर्मित',
    disclaimer: 'यह रिपोर्ट सूचनात्मक उद्देश्यों के लिए है। आधिकारिक पात्रता सरकारी विभाग द्वारा निर्धारित की जाएगी।',
    qr: 'QR', page: 'पृष्ठ 1',
  },
};

const CSS = `
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 13px; color: #1a1a1a; background: #fff; padding: 24px; }
.report { max-width: 860px; margin: 0 auto; }
.header { display: flex; justify-content: space-between; align-items: flex-start; padding-bottom: 20px; }
.logo-wrap { display: flex; align-items: center; gap: 14px; }
.logo-badge { width: 52px; height: 52px; background: #1a365d; color: white; border-radius: 10px; display: flex; align-items: center; justify-content: center; font-size: 24px; font-weight: 800; }
.logo-name { font-size: 22px; font-weight: 700; color: #1a365d; }
.logo-sub { font-size: 11px; color: #666; margin-top: 2px; }
.meta { text-align: right; }
.meta-title { font-size: 15px; font-weight: 700; color: #1a365d; margin-bottom: 8px; }
.meta-table td { padding: 2px 8px; font-size: 11px; }
.meta-table td:first-child { color: #666; font-weight: 600; }
hr { border: none; border-top: 2px solid #e2e8f0; margin: 18px 0; }
.section-title { font-size: 14px; font-weight: 700; color: #1a365d; margin-bottom: 12px; border-left: 4px solid #1a365d; padding-left: 10px; display: flex; align-items: center; gap: 8px; }
.badge { background: #1a365d; color: white; border-radius: 10px; font-size: 10px; padding: 1px 7px; font-weight: 700; }
.profile-table { width: 100%; border-collapse: collapse; }
.profile-table tr:nth-child(even) td { background: #f7fafc; }
.profile-table td { padding: 7px 12px; border: 1px solid #e2e8f0; font-size: 12px; }
.profile-table td:first-child { font-weight: 600; color: #4a5568; width: 38%; }
.scheme-card { border: 1.5px solid #cbd5e0; border-radius: 8px; overflow: hidden; margin-bottom: 18px; page-break-inside: avoid; }
.scheme-header { background: #1a365d; color: white; padding: 11px 16px; display: flex; align-items: center; gap: 12px; }
.scheme-rank { font-size: 10px; background: rgba(255,255,255,0.2); border-radius: 4px; padding: 2px 8px; font-weight: 700; }
.scheme-name { font-size: 13px; font-weight: 700; flex: 1; }
.scheme-score { font-size: 10px; background: rgba(255,255,255,0.15); border-radius: 4px; padding: 2px 8px; white-space: nowrap; }
.scheme-cats { padding: 7px 14px; background: #edf2f7; display: flex; gap: 6px; flex-wrap: wrap; }
.cat-badge { font-size: 10px; padding: 2px 8px; border-radius: 4px; font-weight: 600; }
.cat-level { background: #bee3f8; color: #2b6cb0; }
.cat-cat { background: #c6f6d5; color: #276749; }
.scheme-table { width: 100%; border-collapse: collapse; }
.scheme-table td { padding: 7px 14px; border-top: 1px solid #e2e8f0; font-size: 11.5px; vertical-align: top; }
.scheme-table td:first-child { font-weight: 600; color: #4a5568; width: 20%; background: #f7fafc; white-space: nowrap; }
.reasons { padding: 8px 14px; background: #f0fff4; border-top: 1px solid #c6f6d5; }
.reasons-label { font-size: 10px; font-weight: 700; color: #276749; margin-bottom: 5px; }
.reasons ul { padding-left: 16px; }
.reasons li { font-size: 11px; color: #276749; margin-bottom: 2px; }
.summary-box { background: #f7fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; font-size: 12px; line-height: 1.7; white-space: pre-wrap; }
.footer { display: flex; align-items: flex-start; gap: 20px; border-top: 2px solid #e2e8f0; padding-top: 16px; margin-top: 28px; }
.qr { width: 60px; height: 60px; border: 2px dashed #cbd5e0; border-radius: 6px; display: flex; align-items: center; justify-content: center; font-size: 10px; color: #999; }
.footer-center { flex: 1; }
.footer-brand { font-size: 13px; font-weight: 700; color: #1a365d; }
.footer-ts { font-size: 11px; color: #718096; margin-top: 3px; }
.footer-disc { font-size: 10px; color: #999; margin-top: 5px; line-height: 1.5; }
.footer-page { font-size: 11px; color: #718096; white-space: nowrap; }
@media print {
  body { padding: 0; }
  .scheme-card, .section { page-break-inside: avoid; }
  h2 { page-break-after: avoid; }
}
`;

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export function buildPdfHtml(opts: PdfReportOptions): string {
  const { profile, recommendations, applicationId, generatedDate, language, conversationSummary } = opts;
  const l = L[language];

  const disabilityVal = profile.disabilityStatus === true ? l.yes : profile.disabilityStatus === false ? l.no : '—';
  const profileRows = [
    [l.fields.name,       profile.name           ?? '—'],
    [l.fields.age,        profile.age != null ? String(profile.age) : '—'],
    [l.fields.gender,     profile.gender         ?? '—'],
    [l.fields.state,      profile.state          ?? '—'],
    [l.fields.category,   profile.category       ?? '—'],
    [l.fields.occupation, profile.occupation     ?? '—'],
    [l.fields.income,     profile.income != null ? `₹${profile.income.toLocaleString('en-IN')}` : '—'],
    [l.fields.disability, disabilityVal],
    [l.fields.marital,    profile.maritalStatus  ?? '—'],
  ];

  const profileTableHtml = profileRows.map(([k, v]) =>
    `<tr><td>${esc(k)}</td><td>${esc(String(v))}</td></tr>`
  ).join('');

  const schemesHtml = recommendations.length === 0
    ? `<p style="color:#999;font-style:italic">${l.noSchemes}</p>`
    : recommendations.map((rec, idx) => `
      <div class="scheme-card">
        <div class="scheme-header">
          <span class="scheme-rank">${l.rank} #${idx + 1}</span>
          <span class="scheme-name">${esc(rec.schemeName)}</span>
          <span class="scheme-score">${l.score}: ${rec.score}</span>
        </div>
        <div class="scheme-cats">
          ${rec.level ? `<span class="cat-badge cat-level">${esc(rec.level)}</span>` : ''}
          ${rec.category.slice(0,3).map(c => `<span class="cat-badge cat-cat">${esc(c)}</span>`).join('')}
        </div>
        <table class="scheme-table">
          <tr><td>${l.benefits}</td><td>${esc(rec.benefits || '—')}</td></tr>
          <tr><td>${l.eligibility}</td><td>${esc(rec.eligibilityText || '—')}</td></tr>
          <tr><td>${l.documents}</td><td>${esc(rec.documents || '—')}</td></tr>
          <tr><td>${l.application}</td><td>${esc(rec.application || '—')}</td></tr>
        </table>
        ${rec.reasons.length > 0 ? `
        <div class="reasons">
          <div class="reasons-label">${l.matchReasons}</div>
          <ul>${rec.reasons.map(r => `<li>${esc(r)}</li>`).join('')}</ul>
        </div>` : ''}
      </div>
    `).join('');

  const summaryHtml = conversationSummary ? `
    <hr/>
    <div class="section">
      <div class="section-title">${l.summaryTitle}</div>
      <div class="summary-box">${esc(conversationSummary)}</div>
    </div>
  ` : '';

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <title>Sahayak AI — Application Report</title>
  <style>${CSS}</style>
</head>
<body>
<div class="report">
  <div class="header">
    <div class="logo-wrap">
      <div class="logo-badge">S</div>
      <div>
        <div class="logo-name">Sahayak AI</div>
        <div class="logo-sub">${language === 'hi' ? 'सरकारी कल्याण सहायक' : 'Government Welfare Assistant'}</div>
      </div>
    </div>
    <div class="meta">
      <div class="meta-title">${l.title}</div>
      <table class="meta-table">
        <tr><td>${l.appId}</td><td>${esc(applicationId)}</td></tr>
        <tr><td>${l.generated}</td><td>${esc(generatedDate)}</td></tr>
        <tr><td>${l.lang}</td><td>${l.langName}</td></tr>
        <tr><td>${l.citizen}</td><td>${esc(profile.name ?? '—')}</td></tr>
      </table>
    </div>
  </div>
  <hr/>
  <div class="section">
    <div class="section-title">${l.profileTitle}</div>
    <table class="profile-table"><tbody>${profileTableHtml}</tbody></table>
  </div>
  <hr/>
  <div class="section">
    <div class="section-title">${l.schemesTitle} <span class="badge">${recommendations.length}</span></div>
    ${schemesHtml}
  </div>
  ${summaryHtml}
  <div class="footer">
    <div class="qr">${l.qr}</div>
    <div class="footer-center">
      <div class="footer-brand">${l.footerBrand}</div>
      <div class="footer-ts">${esc(generatedDate)}</div>
      <div class="footer-disc">${l.disclaimer}</div>
    </div>
    <div class="footer-page">${l.page}</div>
  </div>
</div>
</body>
</html>`;
}

// Keep React component export for backward compat (unused now)
export const PdfReport = () => null;
export default PdfReport;
