/**
 * backendStrings.ts
 * All user-facing strings generated by the backend, keyed by language.
 * Single source of truth for multilingual backend messages.
 * To add a new language: add a new key to every Record below.
 */

export type SupportedLanguage = 'en' | 'hi';

/** Injected at the top of every LLM system prompt to enforce output language */
export const LANGUAGE_INSTRUCTION: Record<SupportedLanguage, string> = {
  en: 'IMPORTANT: You MUST respond ONLY in English. Do not use any other language.',
  hi: 'महत्वपूर्ण: आपको केवल हिंदी में उत्तर देना है। देवनागरी लिपि का उपयोग करें। किसी भी अन्य भाषा का उपयोग न करें।',
};

/** Initial greeting shown when a new session starts */
export const GREETING: Record<SupportedLanguage, string> = {
  en: "Hello! I am Sahayak AI, your caseworker assistant. Let's start by understanding the citizen's profile. You can speak naturally, or write a statement like: 'I am Ram, a farmer from Bihar, married and earning ₹90,000 per year.'",
  hi: "नमस्ते! मैं सहायक AI हूँ, आपका केसवर्कर सहायक। आइए नागरिक की प्रोफ़ाइल समझने से शुरुआत करें। आप स्वाभाविक रूप से बोल सकते हैं, जैसे: 'मेरा नाम राम है, मैं बिहार का किसान हूँ, विवाहित हूँ और सालाना ₹90,000 कमाता हूँ।'",
};

/** Questions asked when a profile field is missing */
export const MISSING_FIELD_QUESTIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    name: "Could you please tell me the citizen's full name?",
    age: "What is the applicant's age?",
    gender: "What is the applicant's gender? (Male/Female/Other)",
    state: "Which state is the applicant from?",
    income: "What is the applicant's annual family income (in ₹)?",
    occupation: "What is the applicant's occupation? (e.g., Farmer, Student, Construction Worker)",
    maritalStatus: "What is the applicant's marital status? (Single/Married/Widowed/Divorced)",
    category: "Which social category does the applicant belong to? (General, OBC, SC, ST)",
    disabilityStatus: "Does the applicant have any physical disability? (Yes/No)",
    default: "Could you please provide more details about the citizen?",
  },
  hi: {
    name: "कृपया नागरिक का पूरा नाम बताएं?",
    age: "आवेदक की उम्र क्या है?",
    gender: "आवेदक का लिंग क्या है? (पुरुष/महिला/अन्य)",
    state: "आवेदक किस राज्य से है?",
    income: "आवेदक की वार्षिक पारिवारिक आय (₹ में) कितनी है?",
    occupation: "आवेदक का व्यवसाय क्या है? (जैसे, किसान, छात्र, निर्माण मजदूर)",
    maritalStatus: "आवेदक की वैवाहिक स्थिति क्या है? (अविवाहित/विवाहित/विधवा/तलाकशुदा)",
    category: "आवेदक किस सामाजिक श्रेणी से है? (सामान्य, OBC, SC, ST)",
    disabilityStatus: "क्या आवेदक को कोई शारीरिक विकलांगता है? (हाँ/नहीं)",
    default: "कृपया नागरिक के बारे में अधिक जानकारी प्रदान करें।",
  },
};

/** Shown when profile is complete and recommendations are ready */
export const PROFILE_COMPLETE_MESSAGE: Record<SupportedLanguage, string> = {
  en: "I have successfully compiled the citizen's profile and identified the top welfare schemes they qualify for. You can review the recommendations and report in the panel on the right.",
  hi: "मैंने सफलतापूर्वक नागरिक की प्रोफ़ाइल तैयार की है और उन शीर्ष कल्याण योजनाओं की पहचान की है जिनके लिए वे पात्र हैं। दाईं ओर के पैनल में सिफारिशें और रिपोर्ट देखें।",
};

/** Shown when recommendation engine throws an error */
export const PROFILE_ERROR_MESSAGE: Record<SupportedLanguage, string> = {
  en: "I have collected the profile details, but encountered an error generating recommendations. Please check your vector database and connection.",
  hi: "मैंने प्रोफ़ाइल विवरण एकत्र किया है, लेकिन सिफारिशें तैयार करते समय एक त्रुटि हुई। कृपया अपना वेक्टर डेटाबेस और कनेक्शन जाँचें।",
};

/** Shown when the full application form is completed */
export const APPLICATION_COMPLETE_MESSAGE: Record<SupportedLanguage, (schemeName: string) => string> = {
  en: (schemeName) =>
    `Great! I have collected all the application details for **${schemeName}** and compiled a professional Casework Application Summary. You can review and print it in the workspace panel.`,
  hi: (schemeName) =>
    `बहुत अच्छा! मैंने **${schemeName}** के लिए सभी आवेदन विवरण एकत्र किए हैं और एक पेशेवर केसवर्क आवेदन सारांश तैयार किया है। कार्यक्षेत्र पैनल में इसे देखें और प्रिंट करें।`,
};

/** Shown when no schemes match the profile */
export const NO_SCHEMES_FOUND: Record<SupportedLanguage, string> = {
  en: "Based on the applicant's profile, no matching government schemes were found in our database.",
  hi: "आवेदक की प्रोफ़ाइल के आधार पर, हमारे डेटाबेस में कोई मिलान करने वाली सरकारी योजनाएं नहीं मिलीं।",
};
